@extends('layouts.app')
@section('content')
<div class="space-y-6">
    <x-ui.page-header title="Grades" subtitle="Kelola master grade untuk kebutuhan assignment dan evaluasi level." :breadcrumbs="[['label' => 'Master'], ['label' => 'Grades']]">
        <x-slot:actions>
            @if(auth()->user()->hasPermission('grade.manage'))<x-ui.button variant="primary" onclick="window.location='{{ route('master.grades.create') }}'">Add Grade</x-ui.button>@endif
        </x-slot:actions>
    </x-ui.page-header>
    <x-ui.page-section title="Grade Directory" subtitle="Cari grade berdasarkan kode, nama, atau level order.">
        <form method="GET" action="{{ route('master.grades.index') }}" class="grid gap-4 lg:grid-cols-[minmax(0,1fr)_220px_auto]">
            <x-ui.field label="Search"><input type="text" name="q" value="{{ request('q') }}" placeholder="Cari grade code / grade name" class="w-full rounded-2xl border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-800 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-100"></x-ui.field>
            <x-ui.field label="Status"><select name="active" class="w-full rounded-2xl border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-800 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-100"><option value="">All</option><option value="1" @selected((string) request('active') === '1')>Active</option><option value="0" @selected((string) request('active') === '0')>Inactive</option></select></x-ui.field>
            <div class="flex items-end gap-3"><x-ui.button type="submit">Search</x-ui.button><x-ui.button type="button" variant="ghost" onclick="window.location='{{ route('master.grades.index') }}'">Reset</x-ui.button></div>
        </form>
    </x-ui.page-section>
    <x-ui.table-shell><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50/80"><tr><th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Code</th><th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Name</th><th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Level</th><th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Status</th><th class="px-5 py-3 text-right text-xs font-semibold uppercase tracking-wide text-slate-500">Action</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">@forelse($grades as $grade)<tr class="transition hover:bg-slate-50"><td class="px-5 py-4 font-medium text-slate-900">{{ $grade->grade_code }}</td><td class="px-5 py-4 text-slate-700">{{ $grade->grade_name }}</td><td class="px-5 py-4 text-slate-600">{{ $grade->level_order }}</td><td class="px-5 py-4">@if($grade->active)<span class="inline-flex items-center rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-medium text-emerald-700 ring-1 ring-emerald-200">Active</span>@else<span class="inline-flex items-center rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-700 ring-1 ring-slate-200">Inactive</span>@endif</td><td class="px-5 py-4 text-right">@if(auth()->user()->hasPermission('grade.manage'))<x-ui.button type="button" size="sm" onclick="window.location='{{ route('master.grades.edit', $grade->grade_id) }}'">Edit</x-ui.button>@else<span class="text-xs text-slate-400">No action</span>@endif</td></tr>@empty<tr><td colspan="5" class="px-5 py-14"><x-ui.empty-state title="No grades found" description="Belum ada data grade untuk filter yang sedang dipakai." /></td></tr>@endforelse</tbody></table>@if($grades->hasPages())<div class="border-t border-slate-200 bg-white px-5 py-4">{{ $grades->withQueryString()->links() }}</div>@endif</x-ui.table-shell>
</div>
@endsection
